//自动化渲染尝试
//一共三层 由index作为唯一标识 如果index未定义或者相同会导致展开时出现重复
//嵌套层级用subMenu定义 子菜单由items定义
export const MenuConfig = () => [
    //用户
    {
        title:"用户控制",
        index:"/user",
        icon:"",
        items:[
            {
                index:"/user",
                title:"用户列表",
            },
            //查看权限
            {
                index:"/user/permission",
                title:"查看权限",
            }
        ]
    },
    //产品管理
    {
        title:"资产管理",
        index:"/product",
        icon:"",
        subMenu:[
            {
                index:"/product/list",
                title:"资产列表",
                icon:"",
                items:[
                    {
                        index:"/product/list/controller",
                        title:"集群控制",
                    }
                ],
            },
            {
                index:"/product/view",
                title:"资产视图",
                icon:"",
                items:[
                    {
                        index:"/product/list/view",
                        title:"集群状态",
                    }
                ],
            },
        ]
    },
    {
        title:"樱之杜净梦者",
        icon:"",
        index:"/moridreamers",
        subMenu:[
            {
                title:"女主角们",
                icon:"",
                index:"/moridreamers/girls",
                items:[
                    {
                        title:"桐远暮羽",
                        index:"/moridreamers/girls/muyu",
                    },
                    {
                        title:"秋津圆香",
                        index:"/moridreamers/girls/yuanxiang",
                    },
                    {
                        title:"闲宫真幌",
                        index:"/moridreamers/girls/zhenhuang",
                    },
                    {
                        title:"衿坂美冬",
                        index:"/moridreamers/girls/meidong",
                    },
                    {
                        title:"吹上初音",
                        index:"/moridreamers/girls/miku",
                    },

                ]
            }
        ],
    }
]